package com.m3ir.RestHello;

import javax.websocket.server.PathParam;
import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;
import javax.ws.rs.core.MediaType;

/**
 * Root resource (exposed at "myresource" path)
 */
@Path("/myresource")
public class MyResource {

    @GET
    @Produces(MediaType.TEXT_PLAIN)
    public String Hello() {
        return "HELLO WORLD GENERATED BY REST !";
    }
    
    @GET
    @Path("/myresource/{name}")
    public String getName(@PathParam("name") String name) {
    return name;
    }


}
